[build]
  # No build command needed - just serving static files + functions
  functions = "functions"
  publish = "public"

[functions]
  node_bundler = "esbuild"

# Environment variables
[env.production]
  BREVO_API_KEY = ""
  SENDER_EMAIL = "support@turnkeyai.com.au"
